### ISSUE TITLE
Dockerize + deploy checklist

### ISSUE THREAD

**Issue by chrismckinnel** [eHealthAfrica/ureport#7]
## URLs
- [ ] Create dev, stage and live URLs in Route53
## Setup SES
- [ ] Authorise domain to send emails from app
- [ ] Create SES user
## Setup Sentry
- [ ] Set up sentry for error reporting (need to talk to @nkhumphreys about this)
## Settings
- [ ] Update `settings.py` with SES host / username / password
- [ ] Update `nginx` config with new URLs
- [ ] Fix default `RAVEN_DSN` value, current default is throwing an error
- [ ] Put basic-auth on dev + stage URLs
- [ ] Change dockers exposed port to be 80, having it as 4000 breaks the current ELB health check
- [ ] Stop exposing port 8000 in the `docker-compose.yml` if it's not going to be used
## Changes / improvements
- [ ] Fix logging settings, Django is currently only logging to console, should be logging to files
- [ ] Move nginx to its own container & use superivsor to run it

**Comment by auduaboki** [comment]
Checklist completed. 
Deployment will be attempted.

**Comment by chrismckinnel** [comment]
@auduaboki, tick the items above that you have completed and reference each one with a pull request into the branch `feature/nathan/dockerize`.

E.g.,
- [x] Update `settings.py` with SES host / username / password - [Link to relevant PR](https://github.com/eHealthAfrica/ureport/)
